# Netlify Configuration File for MoonChimp Presale

[build]
  # Base directory - leave empty to use root
  base = ""
  
  # No build command needed for static site
  command = ""
  
  # Publish from the root directory (where your files are)
  publish = "./"

[build.environment]
  NODE_VERSION = "18.17.0"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
